version: '3.6'
services:
  postgres:
    image: postgres:13
    restart: always
    environment: 
        - DATABASE_HOST=127.0.0.1
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=root  
    ports: 
        - "5432:5432"
    volumes: 
        - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  odoo:
    image: odoo:14.0
    ports:
      - 8069:8069
    depends_on:
      - postgres
    restart: always
    command: '-- -d postgres -i base,auth_oauth,auth_oauth_keycloak'
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./odoo/config:/etc/odoo
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/themes:/mnt/themes
      - ./odoo/default:/mnt/addons
    environment:
      HOST: postgres
      USER: odoo
      POSTGRES_PASSWORD: odoo_pg_pass
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always
    command:
      - '-Dkeycloak.profile.feature.upload_scripts=enabled'
      - '-Dkeycloak.migration.action=import'
      - '-Dkeycloak.migration.provider=singleFile'
      - '-Dkeycloak.migration.file=/tmp/master-realm.json'
      - '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING'
    volumes:
      - type: bind
        source: './keycloak/master-realm.json'
        target: '/tmp/master-realm.json'
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
  hasura:
    image: 'hasura/graphql-engine:v2.0.8.cli-migrations-v3'
    ports:
      - '8079:8080'
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
      - ./hasura/seeds:/hasura-seeds
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hasura:hasura@postgres:5432/hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ADMIN_SECRET: vx-template-app-access-key
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "jwk_url": "http://keycloak:8080/auth/realms/master/protocol/openid-connect/certs"}'
  vx-template:
     build:
       context: ./
       dockerfile: Dockerfile.dev
     ports:
       - 80
     restart: unless-stopped
volumes:
  odoo_web_data: